### ISSUE TITLE
warnings

### ISSUE THREAD

**Issue by ArtElleys** [MinecraftForge/Documentation#112]
This is normal ???

08:02:37	launcher	main	warn	Couldn't get hash for net/minecraftforge/forge/1.12-14.21.1.2387/forge-1.12-14.21.1.2387.jar from http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12-14.21.1.2387/forge-1.12-14.21.1.2387.jar.sha1: HTTP 404: Not Found
08:02:37	launcher	main	warn	Have local file C:/Users\Art\AppData\Roaming\.minecraft\libraries\net/minecraftforge/forge/1.12-14.21.1.2387/forge-1.12-14.21.1.2387.jar but don't know what size or hash it should be. Have to assume it's good.
08:02:37	launcher	main	warn	Couldn't get hash for jline/jline/2.13/jline-2.13.jar from http://files.minecraftforge.net/maven/jline/jline/2.13/jline-2.13.jar.sha1: HTTP 404: Not Found
08:02:37	launcher	main	warn	Have local file C:/Users\Art\AppData\Roaming\.minecraft\libraries\jline/jline/2.13/jline-2.13.jar but don't know what size or hash it should be. Have to assume it's good.
08:02:37	launcher	main	warn	Couldn't get hash for com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar from http://files.minecraftforge.net/maven/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar.sha1: HTTP 404: Not Found
08:02:37	launcher	main	warn	Have local file C:/Users\Art\AppData\Roaming\.minecraft\libraries\com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar but don't know what size or hash it should be. Have to assume it's good.
08:02:37	launcher	main	warn	Couldn't get hash for com/typesafe/config/1.2.1/config-1.2.1.jar from http://files.minecraftforge.net/maven/com/typesafe/config/1.2.1/config-1.2.1.jar.sha1: HTTP 404: Not Found
08:02:37	launcher	main	warn	Have local file C:/Users\Art\AppData\Roaming\.minecraft\libraries\com/typesafe/config/1.2.1/config-1.2.1.jar but don't know what size or hash it should be. Have to assume it's good.
08:02:37	launcher	main	warn	Couldn't get hash for org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar from http://files.minecraftforge.net/maven/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar.sha1: HTTP 404: Not Found
08:02:37	launcher	main	warn	Have local file C:/Users\Art\AppData\Roaming\.minecraft\libraries\org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar but don't know what size or hash it should be. Have to assume it's good.
08:02:37	launcher	main	warn	Couldn't get hash for org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar from http://files.minecraftforge.net/maven/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar.sha1: HTTP 404: Not Found
08:02:37	launcher	main	warn	Have local file C:/Users\Art\AppData\Roaming\.minecraft\libraries\org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar but don't know what size or hash it should be. Have to assume it's good.
08:02:37	launcher	main	warn	Couldn't get hash for org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar from http://files.minecraftforge.net/maven/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar.sha1: HTTP 404: Not Found
08:02:37	launcher	main	warn	Couldn't get hash for org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar from http://files.minecraftforge.net/maven/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar.sha1: HTTP 404: Not Found
08:02:37	launcher	main	warn	Couldn't get hash for org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar from http://files.minecraftforge.net/maven/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar.sha1: HTTP 404: Not Found
08:02:37	launcher	main	warn	Couldn't get hash for org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar from http://files.minecraftforge.net/maven/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar.sha1: HTTP 404: Not Found
08:02:37	launcher	main	warn	Couldn't get hash for org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar from http://files.minecraftforge.net/maven/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar.sha1: HTTP 404: Not Found
08:02:37	launcher	main	warn	Have local file C:/Users\Art\AppData\Roaming\.minecraft\libraries\org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar but don't know what size or hash it should be. Have to assume it's good.
08:02:37	launcher	main	warn	Have local file C:/Users\Art\AppData\Roaming\.minecraft\libraries\org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar but don't know what size or hash it should be. Have to assume it's good.
08:02:38	launcher	main	warn	Couldn't get hash for org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar from http://files.minecraftforge.net/maven/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar.sha1: HTTP 404: Not Found
08:02:38	launcher	main	warn	Have local file C:/Users\Art\AppData\Roaming\.minecraft\libraries\org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar but don't know what size or hash it should be. Have to assume it's good.
08:02:38	launcher	main	warn	Have local file C:/Users\Art\AppData\Roaming\.minecraft\libraries\org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar but don't know what size or hash it should be. Have to assume it's good.
08:02:38	launcher	main	warn	Have local file C:/Users\Art\AppData\Roaming\.minecraft\libraries\org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar but don't know what size or hash it should be. Have to assume it's good.
08:02:38	launcher	main	warn	Have local file C:/Users\Art\AppData\Roaming\.minecraft\libraries\org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar but don't know what size or hash it should be. Have to assume it's good.
08:02:38	launcher	main	warn	Couldn't get hash for org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar from http://files.minecraftforge.net/maven/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar.sha1: HTTP 404: Not Found
08:02:38	launcher	main	warn	Have local file C:/Users\Art\AppData\Roaming\.minecraft\libraries\org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar but don't know what size or hash it should be. Have to assume it's good.
08:02:38	launcher	main	info	Checking installations.

**Comment by LexManos** [comment]
Not the place for tech support use the forums.
