### ISSUE TITLE
1.12 Updating screen events  java.lang.IndexOutOfBoundsException: bitIndex < 0: -1

### ISSUE THREAD

**Issue by captcookie** [MinecraftForge/Documentation#116]
https://pastebin.com/E8eNq9mL

When players click the green recipe book...insta crash to the launcher. Forge 2395 Only crashes on multiplayer. Single player works fine.

**Comment by williewillus** [comment]
Wrong repo

**Comment by captcookie** [comment]
I fig out the problem. Edible Tools.
