### ISSUE TITLE
Conventions.Localization mentions en_US when it should be en_us

### ISSUE THREAD

**Issue by Thretcha** [MinecraftForge/Documentation#136]
In the the localization section of the convention page en_US is mentioned as an example language file.
It has to be en_us to actually work.

Also please be so nice and add at least one example like the following
item.<unlocalizedname>.name = desired localized name here

**Comment by Bluexin** [comment]
https://github.com/MinecraftForge/Documentation/pull/148 should fix the first part

**Comment by TehNut** [comment]
The second part is unnecessary in my opinion. It is a basic vanilla resource pack feature.
