### ISSUE TITLE
Conventions are not shown on the docs page

### ISSUE THREAD

**Issue by ThePsionic** [MinecraftForge/Documentation#15]
Per the title, there is no header "Conventions" in the sidebar with the expected "Versioning" article in it.

**Comment by tterrag1098** [comment]
Because you did not add it to the [index](https://github.com/MinecraftForge/Documentation/blob/master/mkdocs.yml)

@LexManos in the future make sure this is done when new pages are added

**Comment by tterrag1098** [comment]
Fixed via #16

**Comment by LexManos** [comment]
That's why i'm looking for people to administer this repo not me.

**Comment by tterrag1098** [comment]
I think I've shown I'm more than willing :P
