### ISSUE TITLE
TileEntity Page broken

### ISSUE THREAD

**Issue by JTK222** [MinecraftForge/Documentation#173]
So, I have no Idea what happened.
But some parts of the TileEntity Page are missing leaving this behind: 
![image](https://user-images.githubusercontent.com/10399186/41497777-b05c9fd2-715c-11e8-86fd-5ed97e239a36.png)

**Comment by tterrag1098** [comment]
Fixed via b63614f9c6af2a6067d8de79f09facc64305b31d
