### ISSUE TITLE
Add mention about sidedness and lambdas

### ISSUE THREAD

**Issue by bs2609** [MinecraftForge/Documentation#178]
As this does seem to come up reasonably regularly, I think it'd be good to have a note warning about using lambdas in proximity to sided code. The SimpleImpl example could possibly also have this mentioned, as the current version passes a lambda to `addScheduledTask`.

**Comment by williewillus** [comment]
I was under the impression lambdas in addScheduledTask work now? At some point back in 1.8/9 I knew it was a problem but I recall using it without issues sometime after.

**Comment by mezz** [comment]
Sounds related to the problem fixed here: https://github.com/MinecraftForge/MinecraftForge/commit/8fbf4cf1158ca74710672a35c51960b6b8df0bbb
Ideally that stuff should work just fine.

**Comment by bs2609** [comment]
The problem I'm referencing is that of https://github.com/MinecraftForge/MinecraftForge/issues/4391.

**Comment by ChampionAsh5357** [comment]
Merged in omnibus #364.
