### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by z3t0** [MinecraftForge/Documentation#19]
Is there anywhere I can find documentation for the API? If not should I work on creating one? That is, will it be possible to actually write an API Reference for this?

**Comment by ThePsionic** [comment]
No one seems to have any pull requests open regarding the API so go ahead

**Comment by z3t0** [comment]
@ThePsionic Any idea what this is referring to?
http://www.minecraftforge.net/wiki/Category:Tutorials/ForgeDocumentation

I could not find any javadoc within the download...

**Comment by tterrag1098** [comment]
What do you mean "the API"? To me all of forge is an API. Could you be more
specific?

**Comment by z3t0** [comment]
@tterrag1098 Please read care fully. I referred to "Documentation" for the API (obv. forge)

**Comment by tterrag1098** [comment]
Are you saying you want to document how to make documentation? You really need to be more clear. You say read carefully but you have barely said anything.

**Comment by z3t0** [comment]
@tterrag1098 Sorry for not being clear.
So I am asking is there any sort of documentation for the API? In the link I provided above it refers to some javadoc but I could not find it...

In that case if there is no documentation, would it be plausible to write it? I could do it but my question is that will it be possible to document Forge? Is the development too rapid?

**Comment by ThePsionic** [comment]
What API are you referring to? You're not making yourself very clear here to be honest.

**Comment by z3t0** [comment]
@tterrag1098 Minecraft Forge

**Comment by bonii-xx** [comment]
I think what you're asking is... "how does Markdown work"? As in how to write files for the documentation?

**Comment by z3t0** [comment]
@bonii-xx Lol sorry.. not sure how but I am clearly not being clear.

I know how to write documentation. I am asking if I should write documentation for the Minecraft Forge API because if the project is not suited to a written reference then there would be no point. Also in terms of the javadoc I don't think that is active any more

**Comment by ThePsionic** [comment]
...you want to write documentation on all of Forge? That's kind of the point of this entire repo...

**Comment by z3t0** [comment]
Now we are getting somewhere. And no, I want to write documentation in regards to the API Reference only nothing else.

**Comment by tterrag1098** [comment]
The javadoc will be integrated into the docs at some point, it's just a question of when. Keep documentation subjects broad, like the existing ones (networking, blockstates, etc).

**Comment by z3t0** [comment]
@tterrag1098 Is there an existing javadoc?

**Comment by tterrag1098** [comment]
As in, a javadoc jar? Or somewhere to which it's deployed? At this point in time no, but @cpw plans to do so at some point.

**Comment by z3t0** [comment]
Any will do

**Comment by chibill** [comment]
If your looking for forge as an api itself everything is basically tied
into Minecraft. So...

**Comment by tterrag1098** [comment]
@z3t0 Now *you* need to read more closely. I said there are none at this time.

**Comment by z3t0** [comment]
Ok
