### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by z3t0** [MinecraftForge/Documentation#20]
Hi all,

I am going to work on creating a full API Documentation for the Forge API.

Only problem is that I cannot seem to get the source code setup with Intellij Idea... the instructions in the README do not work. Thanks

**Comment by tterrag1098** [comment]
I told you in your last issue that we need to work on broad subjects, that focus on a certain part of modding. I still do not know what you mean by "Full API Documentation". Are you planning to document ***everything***?? You do know that we already have quite a few subjects finished and even more underway, correct? The site is live [here](http://mcforge.rtfd.org).
