### ISSUE TITLE
Manual Pages

### ISSUE THREAD

**Issue by enderger** [MinecraftForge/Documentation#202]
Minecraft Forge is a very complex piece of software. While this wiki covers the basics, it certainly is far from exhaustive. I would like to request a new set of pages that document each and every function to help understand how to implement forge better. This system is proven to work by UNIX man pages.

**Comment by tterrag1098** [comment]
I'd love to have exhaustive documentation on every single method, but unfortunately I don't have infinite time. Unless this is you volunteering to write such documentation, this isn't a valid request.

**Comment by enderger** [comment]
I think that this could also be a community effort, with those who have experience with certain methods writing pages on this

**Comment by tterrag1098** [comment]
Sure, but I think you are severely underestimating just how many functions "each and every" is. Minecraft + Forge together easily comprise 10s of thousands of methods. Documenting them all is not feasible. Time is better spent on big-picture explanations of concepts. Some amount of reverse-engineering is required for modding, that's just the way it is. No one is getting paid to write "real" docs.
