### ISSUE TITLE
OreDictionary entries are registered too early due to outdated information

### ISSUE THREAD

**Issue by UpcraftLP** [MinecraftForge/Documentation#207]
The current documentation tells that OreDictionary entries should be registered during preInit, however the registry events fire *after* preInit, which means registering entries to the OreDictionary will not work at that time.

Current version of the Doc at [OreDictionary](https://mcforge.readthedocs.io/en/latest/utilities/oredictionary/ "ReadTheDocs"):
> Add entries to the OreDictionary during the FMLPreInitializationEvent phase, after initializing the blocks and items that you will register.

**Comment by tterrag1098** [comment]
Not updating 1.12.x any longer.
