### ISSUE TITLE
Translation project?

### ISSUE THREAD

**Issue by Meow-J** [MinecraftForge/Documentation#21]
Hello, can I translate this documentation to Chinese? I think this documentation can help Chinese mod developers.

**Comment by Parker8283** [comment]
There's a crowdin project for it. Don't have the link offhand, but google is your friend.

**Comment by ThePsionic** [comment]
Here you go: https://crowdin.com/project/minecraft-forge

**Comment by Meow-J** [comment]
@Parker8283 @ThePsionic Sorry, I mean, this documentation, not commands

**Comment by AbrarSyed** [comment]
Apeprantly ReadTheDocs only supports locaization when using sphinx, we use mkdocs.

**Comment by tterrag1098** [comment]
We could maintain a branch in chinese, and then build multiple branches. That isn't unreasonable, I don't think.

**Comment by Meow-J** [comment]
So.. I'll fork and translate this doc. If you want Chinese translation later, tell me.

**Comment by tterrag1098** [comment]
Let me know when you have something substantial finished and I'll create a branch for you to PR against :)

**Comment by Meow-J** [comment]
@tterrag1098 All right. :3

**Comment by Meow-J** [comment]
@tterrag1098 I'm done, here is the [translation](http://mcforge-cn.readthedocs.org/).
And this is the [project](https://github.com/Meow-J/Forge-Documentation-CN)
so you can create a branch now.

**Comment by LexManos** [comment]
I don't think it's a good idea to start translating the docs. This just leads to more confusion, and loss of any semblance of verification on our end.
I mean, for all I know your 'translation' could just be PENIS repeated a million times. {Not saying that you would but its more hassle then it's worth}
The project is in english, as is most projects that are opensource/on the internet.
It may suck for the non-english readers but it is how it is.
If they need it translated to something else they could always just use google's translator, tho not the best would get the job done. 
I do not approve of doing any officially sanctioned translations.
