### ISSUE TITLE
Linux command on Forge contribution guide

### ISSUE THREAD

**Issue by itsmeow** [MinecraftForge/Documentation#217]
Here at https://mcforge.readthedocs.io/en/latest/forgedev/#eclipse
Reads:
>    Open a terminal/command prompt and navigate it to the directory of your cloned fork.
    Type ./gradlew setupForge and hit enter. Wait until ForgeGradle is done.

As obvious, ./ is not valid on Windows (or mac?, don't quote me on that one)
Should list the valid command for a given OS.

**Comment by sjx233** [comment]
`./gradlew setupForge` on "Unix-like" systems (including Linux & macOS).
`gradlew setupForge` on Windows.

**Comment by itsmeow** [comment]
People have argued that the issue is solved by using Powershell, but it still doesn't work on Command Prompt (which is arguably better because it's faster)

but aside from the minor politics, it should be the proper way (as with ./ it works on both PS and CMD)

**Comment by tterrag1098** [comment]
It doesn't work without in PS though 
![image](https://user-images.githubusercontent.com/3751664/52576169-9877d500-2ded-11e9-9dc3-6f0fb68dba86.png)
