### ISSUE TITLE
gradlew setupDecompWorkspace is not any longer working

### ISSUE THREAD

**Issue by AndersBillLinden** [MinecraftForge/Documentation#218]
From https://mcforge.readthedocs.io/en/latest/gettingstarted/ you can read

4. Open up a command prompt in the folder you created in step (3), then run gradlew setupDecompWorkspace. 

But there is no `setupDecompWorkspace` task any longer.

**Comment by derfl007** [comment]
It's not needed anymore, if you use Eclipse run gradlew eclipse in the folder and inside eclipse run gradlew generateEclipseRuns or if you use IntelliJ just import the build.gradle as a project and run genIntellijRuns inside the project

**Comment by MajorTuvok** [comment]
Why do people keep opening issues for that?!?

**Comment by tterrag1098** [comment]
The docs are not yet fully updated to 1.13.x as it is a forge *beta*. If you want to view the WIP 1.13 docs, use https://mcforge.readthedocs.io/en/1.13.x/

**Comment by CrimsonRed1710** [comment]
> It's not needed anymore, if you use Eclipse run gradlew eclipse in the folder and inside eclipse run gradlew generateEclipseRuns or if you use IntelliJ just import the build.gradle as a project and run genIntellijRuns inside the project

thanks for this, was trying to setup a workspace to get into modding, my only past experience has been terraria modding which requires pretty much no setup
