### ISSUE TITLE
[Server impossible] (net.minecraft.item.crafting.ShapedRecipes@172ca6a) produces unregistered item minecraft:wooden_door

### ISSUE THREAD

**Issue by Prasodym** [MinecraftForge/Documentation#221]
Hello, As I already posted a post in the forum I have massive problems on a server to joinen, get an error immediately (See Figure 1.1) but as soon as I play offline games this problem does not occur.

**Forge version: 14.23.5.2780**
**Modlist:**[https://pastebin.com/AmUULepp](url)
**Lates logs:** [https://pastebin.com/qZUi15ej](url)
[debug.log](https://github.com/MinecraftForge/Documentation/files/3144106/debug.log)

**1.1**
![error](https://user-images.githubusercontent.com/38152214/57175716-314b4900-6e4f-11e9-8cce-b50da33e9a05.PNG)

**Code**
`java.lang.IllegalStateException: Recipe minecraft:wooden_door (net.minecraft.item.crafting.ShapedRecipes@172ca6a) produces unregistered item minecraft:wooden_door (net.minecraft.item.ItemDoor@1978eab7)`

`NetworkDispatcher exception
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Recipe minecraft:wooden_door (net.minecraft.item.crafting.ShapedRecipes@172ca6a) produces unregistered item minecraft:wooden_door (net.minecraft.item.ItemDoor@1978eab7)`

Read more in lates-log.txt
I hope you can do something with it, Ah and thank you in advance!

**Comment by LexManos** [comment]
Use the forum for basic tech support.
