### ISSUE TITLE
PermissionsAPI is out of date

### ISSUE THREAD

**Issue by chorman0773** [MinecraftForge/Documentation#225]
The PermissionsAPI Page in 1.13.x is out of date. 
Specifically, it references an ICommandSender, which does not exist in 1.13. It also provides no information about how to actually use it, without turning a CommandSource into a GameProfile, which can create a privilage escalation for anyone who has the ability to run /execute while not having certain permissions.

**Comment by tterrag1098** [comment]
I removed the page on this, it was completely outdated. Feel free to PR new information if/when it exists.
