### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by kath660** [MinecraftForge/Documentation#232]
What's going on here? Here are a few instances of the same issue occurring. I tried running Forge with almost no mods at all, and the problem persisted. It popped up from the middle of nowhere one day.

[crash-2019-08-03_21.27.07-server.txt](https://github.com/MinecraftForge/Documentation/files/3464525/crash-2019-08-03_21.27.07-server.txt)

[crash-2019-08-03_20.54.36-server.txt](https://github.com/MinecraftForge/Documentation/files/3464522/crash-2019-08-03_20.54.36-server.txt)

[crash-2019-07-28_20.26.53-server.txt](https://github.com/MinecraftForge/Documentation/files/3464523/crash-2019-07-28_20.26.53-server.txt)

[crash-2019-08-03_21.22.55-server.txt](https://github.com/MinecraftForge/Documentation/files/3464524/crash-2019-08-03_21.22.55-server.txt)

**Comment by DaemonUmbra** [comment]
Wrong Repo and try the [Forums](https://minecraftforge.net/forum/) first.
