### ISSUE TITLE
Include Optifine in Forge 1.14.4

### ISSUE THREAD

**Issue by leifadev** [MinecraftForge/Documentation#235]
I love Forge 1.14.4 and it loads my mods correctly. I would love to see an implementation of Optifine or its features in the latest version! :)

**Comment by Tfarcenim** [comment]
no

**Comment by bl4ckscor3** [comment]
OptiFine is a mod that Forge has nothing to do with. It's not Forge's responsibility to make OptiFine work with Forge, it's the other way around. Wait for the OptiFine dev to make his mod compatible with Forge, and you have all the OptiFine features available for Forge 1.14.4.
