### ISSUE TITLE
Config Annotation is outdated

### ISSUE THREAD

**Issue by qouteall** [MinecraftForge/Documentation#246]
https://mcforge.readthedocs.io/en/1.14.x/config/annotations/
The info is outdated.
If no one objects then I will update the things about the config system.

**Comment by Cadiboo** [comment]
Not sure if this is relevant but I’m working on a PR to reimplement the config annotation for 1.15+

**Comment by tterrag1098** [comment]
I've removed the page on config annotations. Feel free to PR new information.
