### ISSUE TITLE
Possible category for legacy content

### ISSUE THREAD

**Issue by Aeltumn** [MinecraftForge/Documentation#254]
Considering the documentation for 1.12.x still exists and there are probably still people who are going to mod for the version: I don't see a problem with having a link somewhere to access the old docs as long as there's a nice big disclaimer that they shouldn't expect any support. I agree #245 wasn't a good solution so I'd suggest the following:

Having a dedicated category for information about legacy versions. Every bit of information that doesn't concern a supported version is banished to this category, this will cause the category to grow in size as new versions keep getting released but I don't think this would be too big of a problem.

This category would contain a main page that has a list of all previous versions with links to the documentation sites for those versions. This main page can have some text about how what the LTS version currently is and how no one should expect support for the other ones.

This section can also have more pages added similar to #216, pages that reword the update primers (just linking them could also do) and explain generally what changed between the versions.

_Note: With "every bit of information that doesn't concern a supported version is banished to this category" I mean that there would be a link to the old version of the documentation site in the main page, not that there would be a subcategory called 1.12.x with everything in there._

**Comment by tterrag1098** [comment]
That sounds fine.
