### ISSUE TITLE
mappings

### ISSUE THREAD

**Issue by irvnriir** [MinecraftForge/Documentation#258]
what does the line
```
mappings channel: 'stable', version: '<<..>>
```
in `[forge]\build.gradle`, affect ?

i'm trying to find this for about an hour .

**Comment by JoJoDeveloping** [comment]
Which mapping version you are using. As in, which of these zip files: http://export.mcpbot.bspk.rs/

**Comment by irvnriir** [comment]
thanks for the response, but i already saw the page, the things that i can't find/realize is:

1. so this is a command to, during build, translate some of the processed/{source code 's} commands using remote MCPBot pack of snippets/functions ?
2. where is it from, is it a function provided by Forge MDK ?
3. does it require internet or the packs can be put in some folder that is watched by the script ?
4. is it required by the Forge/Build itself ?

**Comment by JoJoDeveloping** [comment]
1) It's a configuration option.
2) Yes, part of [ForgeGradle](https://github.com/MinecraftForge/ForgeGradle/).
3) Yes, it requires the internet. Unless the file is already in the gradle cache, then it isn't downloaded.
4) Yes. Without it you won't get the minecraft binary to link again, which means you code can't be decompiled

**Comment by irvnriir** [comment]
@JoJoDeveloping , thank you .

3. its enough to put the MCPBot's .. ".csv" files into the Gradle Cache Location ? (sor, but can't test right now)
4. did you mean "compiled" ?

**Comment by tterrag1098** [comment]
Issues are not the place for support. Ask on the forums or discord.
