### ISSUE TITLE
Google search finds tterrag.readthedocs.io instead of https://mcforge.readthedocs.io/

### ISSUE THREAD

**Issue by TheGreyGhost** [MinecraftForge/Documentation#261]
Google search finds an old version of the docs:  https://documentation-tterrag.readthedocs.io/en/latest/

Perhaps documentation-tterrag.readthedocs.io could be retired or alternatively updated to redirect to mcforge.readthedocs.io?

**Comment by tterrag1098** [comment]
I can't fix what Google chooses to display, but I have marked my testing versions as private. Hopefully this eventually removes them from the index.

**Comment by diesieben07** [comment]
> I can't fix what Google chooses to display

`<meta name="robots" content="noindex" /`

**Comment by TheGreyGhost** [comment]
OK.  

Another suggestion if dieSieben's doesn't work - perhaps add a prominent link on the front page of your documentation-tterag  (i.e. to send to mcforge.readthedocs.io)?

**Comment by tterrag1098** [comment]
@diesieben07 I can't change it *now*. I already said I took down my public fork, so it's up to google to reindex...

**Comment by TheGreyGhost** [comment]
FYI I've also had this problem before.

How I got it resolved (request Google to reindex the URL):
https://support.google.com/webmasters/answer/6065812?hl=en

**Comment by diesieben07** [comment]
> I can't change it now. I already said I took down my public fork, so it's up to google to reindex...

Its still up though...? What am I missing?

**Comment by tterrag1098** [comment]
They are private, i.e. not indexable.

**Comment by diesieben07** [comment]
??? https://documentation-tterrag.readthedocs.io/en/latest/ is publicly accessible.
It does not contain any note to robots to not index it.
robots.txt also does not seem to exist.

Maybe I am stupid, but I do not see why this would not be indexed by google.
