### ISSUE TITLE
The Version 1.15 documentation Branch is outdated.

### ISSUE THREAD

**Issue by busti** [MinecraftForge/Documentation#262]
Important changes made to the 1.14 branch, i.e. in #239 have not been applied to the 1.15 branch yet.  
This might be a bit confusing for new users since they would select the 1.15 docs initially over the 1.14 docs on readthedocs.io.

**Comment by Aeltumn** [comment]
It would really help if the 1.14 branch was merged into 1.15 as more and more people are making PR's now that are really not necessary as everything is already updated.
