### ISSUE TITLE
[1.15.2] Tree Features don't work with different placement/configs 

### ISSUE THREAD

**Issue by Zathrox** [MinecraftForge/Documentation#270]
Not sure if this is the place to put this or if this is even a bug or intended? but after testing with several placement options and making my own, all the vanilla tree features do not work with the difference placement options and spawn at all layers / levels.

Is this intended in the game code / forge? or a bug?

If it is intended, could forge possibly add something to amend this? it'll add extra biome customizability if you can control the tree conditions for spawning!

**Comment by tterrag1098** [comment]
Not the place.
