### ISSUE TITLE
Broken link in Getting Started

### ISSUE THREAD

**Issue by mdamien** [MinecraftForge/Documentation#277]
Hi, looks like there's a parsing error in the doc here: The files server link is broken

![image](https://user-images.githubusercontent.com/1469823/79694740-8952a980-8272-11ea-9706-eff6734e540e.png)

Link: https://mcforge.readthedocs.io/en/latest/gettingstarted/#from-zero-to-modding

**Comment by Aeltumn** [comment]
This has been fixed on the 1.14.x branch already.
