### ISSUE TITLE
A lack of localization in docs

### ISSUE THREAD

**Issue by zhugeo** [MinecraftForge/Documentation#287]
Hello! The I a bad in a English language, so I want to translate documentation to `Russian` and `Ukrainian` languages. Are this changes possible? If docs translating is possible, how can I do this? (New branch, etc...)

**Comment by FinnT730** [comment]
You would make a PR

**Comment by gigaherz** [comment]
See the last comment in #21

**Comment by zhugeo** [comment]
All right.
