### ISSUE TITLE
Minecraft 1.15.x by default

### ISSUE THREAD

**Issue by filips123** [MinecraftForge/Documentation#289]
Currently, both this GitHub project and documentation use 1.15.x as default branch and default version when viewing documentation. Given that Minecraft 1.15.x is currently the latest version and old Forge 1.14.x is currently LTS, shouldn't default branch and version also be 1.15.x?

From existing issues I see that 1.15.x documentation was outdated in comparison with 1.14.x at some point. If this is still the case, it should be fixed. Also, making 1.15.x the default branch would probably fix too much PRs for 1.14.x branch because GitHub by default clones (and then makes PR) to default branch.

**Comment by tterrag1098** [comment]
1.15.x isn't the default documentation, it's just the latest. I use 1.14.x as the base branch because it keeps merging clean. I can't merge back from 1.15 to 1.14 without cherry picking.
