### ISSUE TITLE
404 Page fails to load CSS/JS using base_url

### ISSUE THREAD

**Issue by GhostFire90** [MinecraftForge/Documentation#293]
https://mcforge.readthedocs.io/en/1.14.x/blocks/interaction/GUIs

Did this portion of the site get removed or is the site bugging? i could really use that rn

**Comment by DaemonUmbra** [comment]
It appears that page was removed, and this error is due to the 404 page not having a correct path to the css

**Comment by GhostFire90** [comment]
Thats too bad. Do you think it got moved to a different location?

**Comment by gigaherz** [comment]
Took a quick peek at the blame info .... that page has never existed. 
This is when that paragraph was added, in 2016: <https://github.com/MinecraftForge/Documentation/tree/c7a7cbde42b97eae48737eb6e9a7933898700cb8/docs/blocks>
it was written *with* the link, but the target has never existed.

**Comment by GhostFire90** [comment]
woah, thats sorta odd. Thanks for letting me know, should I keep this open so they can see it?

**Comment by tterrag1098** [comment]
Editing this issue to reflect the styling problem, the page missing is out of scope. @PaleoCrafter the theme uses `{{ base_url }}` to fill in these stylesheet references, but apparently that's not available on a 404 page? Not sure, needs more investigation.

**Comment by GhostFire90** [comment]
Is there supposed to be a site here that never got done?

**Comment by ChampionAsh5357** [comment]
Fixed via #424.
