### ISSUE TITLE
Blockstates page contains incorrect information

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/Documentation#310]
On the page describing how to use BlockStates, the helper classes that implement `IProperty<T>` are notated in postfix (PropertyBool) instead of the correct prefix (BooleanProperty)

**Comment by TheCurle** [comment]
I presume they're remnants left from the old ways. The 1.14+ documentation was copied from 1.12.2 IIRC, before the refactor that inverted the order of the names of a lot of classes.

**Comment by ghost** [comment]
Yeah, according to some users on the forums, this change happened in 1.13. 
Threw together a small PR (above) that fixes this. 
If I'm gonna complain, I might as well put up the work, right?

**Comment by TheCurle** [comment]
Better than some we've had here.
I haven't a clue who has write access to this repo, i'm presuming tterrag, giga and Lex.

**Comment by gigaherz** [comment]
I'm readonly here. terrag is the primary maintainer

**Comment by TheCurle** [comment]
That's good to know for the future.
Nothing to do but wait.
