### ISSUE TITLE
"detailed" documentation

### ISSUE THREAD

**Issue by sebastianbhahn** [MinecraftForge/Documentation#330]
but nothing about entities or ai smdh

**Comment by Yunus1903** [comment]
The docs are community made.
If you see that something is missing, feel free to make a PR and add it yourself.

**Comment by TheCurle** [comment]
Instead of complaining with no constructiveness whatsoever, I suggest you crack on and make a PR fixing the problems you have with the Docs.
There simply aren't enough hours in the day. Docs are not a priority. Fixing the game-crashing bugs is.
