### ISSUE TITLE
What is maxDamage?

### ISSUE THREAD

**Issue by isosceles3** [MinecraftForge/Documentation#337]
In the Items documentation there is the term maxDamage.  Does this refer to the amount of damage it can do to a player or does it refer to the amount of damage the item takes before breaking?

**Comment by PellucidDice** [comment]
It's the amount of damage it can take before it breaks.

**Comment by sciwhiz12** [comment]
It can also be thought of as the maximum durability of the item.
Closing this, as the description of the `maxDamage` property is clear enough (if anyone thinks otherwise, please leave a comment).
