### ISSUE TITLE
Links to the ForgeGradle cookbook do not work.

### ISSUE THREAD

**Issue by Giacomino99** [MinecraftForge/Documentation#344]
There is a link in the Getting Started page about something called the ForgeGradle cookbook.

It seems that these links lead to a dead page.

https://forgegradle.readthedocs.org/en/latest/cookbook/

**Comment by TheCurle** [comment]
This is intentional. The ForgeGradle cookbook was horrendously outdated, and only had content for FG1.

**Comment by Giacomino99** [comment]
Is there a reason that the links are still in the documentation if they are no longer functional?

**Comment by TheCurle** [comment]
We forgot to remove it. I made a PR to fix that.
