### ISSUE TITLE
Expermental Worlds Crash 1.16.3 - 34.1.18

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/Documentation#346]
I have a personal modpack, when I updated to 34.1.18 it loaded to the menu, but then once i tried to load the world it crashed, after many things I tried, running with no mods, a few, etc. etc., I realized its a bug with creating non official biomes and structures from mods like Biomes O' Plenty and Immersive engineering, once I set it to not use experimental world options, it loaded perfectly fine. If you need anymore info, Ill be glad to provide.

**Comment by TheCurle** [comment]
This has nothing to do with the documentation of Forge. Ask the forums: https://forums.minecraftforge.net/

**Comment by ghost** [comment]
My Bad, sorry
