### ISSUE TITLE
One big typo issue/pr

### ISSUE THREAD

**Issue by Kyu** [MinecraftForge/Documentation#351]
Hi, I was going to request a fix on a typo here: https://mcforge.readthedocs.io/en/latest/concepts/sides/, someone put "snipped" when it should be "snippet", but I didn't want to make an entire PR just for one word. 

I was wondering what the maintainers thought of having one PR for typos people might notice, that anyone can contribute to.

**Comment by sciwhiz12** [comment]
The general idea is that, when possible, small typos should be collected into an 'omnibus' PR, so only one PR needs to be merged for these small fixes.
Right now, we probably won't be accepting that type of PR until the backlog of PRs have been addressed. But after that, we'll see if there are still typos and such that warrant an omnibus PR.
Will leave this open for now for discussions about such a PR in the future.

**Comment by ChampionAsh5357** [comment]
Merged in omnibus #364.
