### ISSUE TITLE
Missing Page: Interaction/Guis

### ISSUE THREAD

**Issue by Draco18s** [MinecraftForge/Documentation#353]
In this section there is a link:
https://mcforge.readthedocs.io/en/1.16.x/blocks/interaction/#guis
> More about GUIs can be found on their page.

That link is 404.

**Comment by ChampionAsh5357** [comment]
This is a duplicate of #74. As for the circumstance, we're addressing all of the issues and PRs currently.

**Comment by Draco18s** [comment]
Jesus I had no idea it had been around so long. :+1:
