### ISSUE TITLE
gi

### ISSUE THREAD

**Issue by Dwaitp** [MinecraftForge/Documentation#359]

**Comment by Dwaitp** [comment]
![bitmoji](https://sdk.bitmoji.com/render/panel/fbd068f0-7ff1-47e5-8053-95a9f75ff4e3-5993904c-6d1f-441e-ae9c-a89a39c44472-v1.png?transparent=1&palette=1&width=246)

**Comment by TheCurle** [comment]
What the fuck?

**Comment by ravenbuilder934** [comment]
the fuck

**Comment by 50ap5ud5** [comment]
I think it's a bot
