### ISSUE TITLE
Pointing at the forums for icons

### ISSUE THREAD

**Issue by LexManos** [MinecraftForge/Documentation#366]
https://github.com/MinecraftForge/Documentation/blob/a1f909e83d9a79a8691300679d3102debb2b61bc/forge_theme/base.html#L9-L18

That stuff needs to be pushed to the files server or hosted on here somewhere. As 
1) the old /forum/ path is outdated/wrong
2) the forums are super heavy processing for each request so using the normal files server is just a simple flat file front end.

**Comment by ChampionAsh5357** [comment]
Merged in omnibus #364.
