### ISSUE TITLE
Issue while starting forge-1.16.5-36.1.0-installer server.

### ISSUE THREAD

**Issue by XipsAhoy** [MinecraftForge/Documentation#367]
Can someone help me, for some reason everytime I start my forge server all my mods get deleted!

[debug.log](https://github.com/MinecraftForge/Documentation/files/6266371/debug.log)
[latest.log](https://github.com/MinecraftForge/Documentation/files/6266372/latest.log)

**Comment by TheCurle** [comment]
This is not the right place for tech support.

Come to [The Forge Discord](https://discord.gg/UvedJ9m).
