### ISSUE TITLE
1.16.5 Not showing in version list

### ISSUE THREAD

**Issue by Underplayer97** [MinecraftForge/Documentation#371]
Hello, I was trying to download Forge 1.16.5-36.1.4 and I was not able to find the version in my Minecraft Launcher. I looked in the Minecraft versions and found that its missing forge-1.16.5-36.1.4.jar but it still had 1.16.5-forge-36.1.4.json. I looked at the .json file using Notepad ++ and noticed that the .jar file that is supposed to be in there, it did not have a url of "net/minecraftforge/forge/1.16.5-36.1.4/forge-1.16.5-36.1.4.jar", which I expected that was the problem. Im posting a picture of what I see of the version folder and the .json file information.
![Forge 1 16 5 Error](https://user-images.githubusercontent.com/66751151/115078445-9e860680-9ecd-11eb-9cf6-687802417800.png)
![1 16 5 36 1 4 json file error](https://user-images.githubusercontent.com/66751151/115078446-9f1e9d00-9ecd-11eb-8a7f-b0cc79e26eb5.png)

**Comment by TheCurle** [comment]
This is not even nearly the correct repo for this issue. 
Ask the [Forums](https://forums.minecraftforge.net/).
