### ISSUE TITLE
Adding custom Recipe Types

### ISSUE THREAD

**Issue by DasHeinzchen** [MinecraftForge/Documentation#379]
I would like to see a page about how to create custom Recipe Types.
I already did some research and I'm really confused aubout those serializers.

**Comment by queekusme** [comment]
My implementation requires an access transformer however feel free to have a look at how i have it implemented
https://github.com/queekusme/Pizza-Chef/blob/1.17.x/src/main/java/com/queekus/pizzachef/crafting/ModCrafting.java

Hope this clears bits up but agree a page in the docs would be useful for those who haven't yet tried doing this...
