### ISSUE TITLE
Where is the actual documentation?

### ISSUE THREAD

**Issue by v-maxson** [MinecraftForge/Documentation#395]
[This](https://mcforge.readthedocs.io/en/1.17.x/) website is apparently the official forge documentation. But I can't seem to find specific documentation for classes. An example, where would I find documentation for the `Block` class specifically (or other classes)? It seems to be just basic descriptions of concepts rather than actual documentation. Am I missing something on this page?

(Apologies if this is the wrong place to ask for this)

**Comment by TheCurle** [comment]
Documenting the entire game of Minecraft would be a monumental task that so far hasn't been acheived once in the history of the game.

It's so large that fully documenting the function of each class and method would take years, and you'd miss the updates to the game that came between now and then.

So, the answer to your question is that it doesn't exist. It can't exist, to be honest. It'd require a time machine.

**Comment by v-maxson** [comment]
Thanks for the quick reply.
