### ISSUE TITLE
Highlight.js does not support JSON comments

### ISSUE THREAD

**Issue by ChampionAsh5357** [MinecraftForge/Documentation#430]
Although GitHub codeblocks support to use of different JSON configurations (`json5`, `jsonc`), Highlight.js does not support commented json. Instead, it actively resolves the script between either `coffeescript` (causing the highlighting errors) and `php` (which surprisingly works without any issue).

To support JSON with comments, it was recommended to use the [JS highlighter](https://github.com/highlightjs/highlight.js/pull/425#issuecomment-35970516) or to create our own distribution of highlight.js.

**Comment by sciwhiz12** [comment]
Addressed by #433.
