### ISSUE TITLE
Custom registry documentation needs updating

### ISSUE THREAD

**Issue by sekwah41** [MinecraftForge/Documentation#452]
Currently, the old documentation is listed for 1.19

https://mcforge.readthedocs.io/en/1.19.x/concepts/registries/#methods-for-registering

Should use RegisterEvent rather than the old versions.

**Comment by sekwah41** [comment]
If I get some time later I'll raise a pr

**Comment by ChampionAsh5357** [comment]
Covered in #451.

**Comment by sekwah41** [comment]
Oh perfect :D
