### ISSUE TITLE
minecraft forge wiki from files.minecraftforge.net

### ISSUE THREAD

**Issue by sudopluto** [MinecraftForge/Documentation#47]
I'm sure if this is the right place to report this, but the link to the wiki from that page points to files.minecraftforge.net/wiki instead of minecraftforge.net/wiki

**Comment by tterrag1098** [comment]
Where is this link? Could you please provide any information at all?

**Comment by bonii-xx** [comment]
He's talking about the Navbar at the top of http://files.minecraftforge.net

**Comment by cpw** [comment]
This is likely a short term problem while we're moving servers about.

**Comment by LexManos** [comment]
Im more inclined to just remove the wiki entirely in favor of the RTDs

**Comment by bonii-xx** [comment]
I was surprised that it didn't point to RTD already.

**Comment by sudopluto** [comment]
Okay I just checked and verified that the link now points to RTD. Closing the issue.
