### ISSUE TITLE
1.19.2 is considered as latest

### ISSUE THREAD

**Issue by tmvkrpxl0** [MinecraftForge/Documentation#475]
![image](https://user-images.githubusercontent.com/41675181/212476873-e184bab1-d02c-4ccb-9581-5f294d5160ce.png)
As it is shown in the photo, it suggests 1.19.2 when 1.19.x should be considered as latest

**Comment by ChampionAsh5357** [comment]
Seems to be an upstream issue due to a missing sanity check, at least that's what I've determined. I've created an [issue on RTD](https://github.com/readthedocs/readthedocs.org/issues/10046) in the meantime to see if they can provide any additional information or fix the issue.

**Comment by ChampionAsh5357** [comment]
Fixed upstream by readthedocs/readthedocs.org#10326
