### ISSUE TITLE
1.19.2 is not shown on 1.19
X page

### ISSUE THREAD

**Issue by tmvkrpxl0** [MinecraftForge/Documentation#495]
Opening version selection menu on 1.19.x does not show 1.19.2 as option, but 1.18.x has it as one of options.

**Comment by ChampionAsh5357** [comment]
The 1.18.x version should no longer have any reference to the 1.19.2 pages since it was removed from 1.19.x in 1.19.4. I can do a quick fix of this later today.

**Comment by ChampionAsh5357** [comment]
Closed by b33358222d5b7eb5dce90f287d66b5374e37ec65
