### ISSUE TITLE
typo 1.19.x docs/gettingstarted/index.md

### ISSUE THREAD

**Issue by pizeroLOL** [MinecraftForge/Documentation#501]
line 41
```markdown
    * **Visual Studio Code**: Run the `getVSCodeRuns` task.
```
 `getVSCodeRuns` should be `genVSCodeRuns` in the https://maven.minecraftforge.net/net/minecraftforge/forge/1.19.4-45.1.2/forge-1.19.4-45.1.2-mdk.zip

**Comment by ChampionAsh5357** [comment]
Closed by https://github.com/MinecraftForge/Documentation/commit/b7e8bbd135893e5aef874fae0592c7573e3eee17
