### ISSUE TITLE
Javadocs location

### ISSUE THREAD

**Issue by clwillingham** [MinecraftForge/Documentation#51]
README.md suggests the javadocs may be hosted somewhere, but does not say where. Will the location be eventually posted? javadocs would be quite useful.

**Comment by tterrag1098** [comment]
Because they are not currently hosted anywhere. It is an open problem because deploying the javadocs for different forge versions would get expensive quick. If you have suggestions, take them up with forge, the docs are just waiting for whenever it eventually happens.
