### ISSUE TITLE
Requesting the Common Ore Dictionary Names listing

### ISSUE THREAD

**Issue by Draco18s** [MinecraftForge/Documentation#69]
This page:
https://web.archive.org/web/20160302193100/http://www.minecraftforge.net/wiki/Common_Oredict_names

Or really, *any* documentation on the Ore Dictionary and its use.

**Comment by tterrag1098** [comment]
:O http://mcforge.readthedocs.io/en/latest/utilities/oredictionary/

**Comment by Draco18s** [comment]
Huh, I'd done a search on it and it wasn't found.  Might want to add an "ore dictionary" redirect.  Because the space fuckered things.
(Either way I'm an idiot)

**Comment by tterrag1098** [comment]
The sort seems broken. CTRL+F always works

**Comment by Draco18s** [comment]
I went to the search bar at first, it failed, I was distracted and didn't think to look through the sidebar.
