### ISSUE TITLE
Request for Documentation for Access Transformers

### ISSUE THREAD

**Issue by mezz** [MinecraftForge/Documentation#87]
They're not hard to use and are a lot cleaner than reflection in most cases. Your code will break at compile-time if mojang changes something, which is not the case with reflection.

The old docs are here but contain tons of outdated info
https://web.archive.org/web/20160814191351/http://www.minecraftforge.net/wiki/Using_Access_Transformers

**Comment by LemADEC** [comment]
A specification is visible here: https://github.com/MinecraftForge/AccessTransformers/blob/master/FMLAT.md
