### ISSUE TITLE
Needed block interaction methods

### ISSUE THREAD

**Issue by elifoster** [MinecraftForge/Documentation#94]
<del>I think it would be useful to have lists of "hooks" (not sure what else you'd call them) in relevant pages. For example, the Block page says that it would be too long to document every single event like function. I agree with that. However, I think having a complete list of them with a brief description would not be that difficult and could be incredibly useful. This would also apply for items and anything else with a similarly huge amount of functions like this. </del>

Here is a list of Block Interaction functions that are not documented yet (1.10.2-12.18.3.2254):
* [ ] onBlockDestroyedByPlayer
* [ ] neighborChanged
* [ ] onBlockAdded
* [ ] breakBlock: Done at #103
* [ ] onBlockDestroyedByExplosion
* [x] onBlockActivated
* [ ] onEntityWalk: Done at #103
* [ ] onBlockClicked
* [ ] onEntityCollidedWithBlock
* [ ] onBlockPlacedBy
* [ ] eventReceived
* [ ] onLanded
* [ ] onBlockHarvested
* [ ] removedByPlayer
* [ ] onBlockExploded
* [ ] onPlantGrow

**Comment by elifoster** [comment]
Actually, it looks like this page has been rewritten since I past read it and is heading in the direction I envisioned.

When I get home, I can make a formal list of Block Interaction functions that should be documented there in this issue (and turn this into a "needed block hooks" issue instead of simply an idea).

**Comment by G-Rath** [comment]
@elifoster I've created a documentation block about the `onLanded` interaction method.

I've tried to lay it out in a structure similar to Oracle's JavaDocs, since I think that's a nice format to stick with. 

Please let me know what you think :)

**Comment by elifoster** [comment]
@G-Rath Yes I like that format. I will update #103 to reflect that format and the position of return/params when I get a chance.
